### ISSUE TITLE
Flag to break loop when detecting a win prevents multiple wins

### ISSUE THREAD

**Issue by incredibleLeitman** [Layusmen/Slot_Machine#4]
https://github.com/Layusmen/Slot_Machine/blob/4e053994538f2cbb36a12ef8b4e5dd45ca326ca2/slot_machine/Program.cs#L53-L54

When breaking after the first found matching line this will prevent the opportunity to hit  a win on multiple lines,
is this intentional in your program or do you maybe want to support this in the future?

**Comment by mayisa87** [comment]
Same issue again there, please fix it

**Comment by mayisa87** [comment]
Issue needs to be reopenend. Did this comment on the commit itself too:

Using continue is not the best choice at this point. Continue and break always affect only the current loop you are in. 
So in case that you detect an mismatch in the inner loop, you set the flag to false, that's fine! But the continue, will jump into the same loop again, so just jump to the start of the inner loop, not outer one!
A break would stop the inner loop, which would make more sense.

As you are now checking on "dismatch" the break would be the right choice! So you detect the mismatch, set variable to false and jump out of inner loop.

Then you check in the if if there was a match in inner loop, if so  you do your further logic (setting horizontalWin to true). Here the continue is not needed at all, as you are at the end of your loop anyway and next iteration starts automatically
